on:
  push:
    branches:
      - master

name: Deploy to S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Build
      id: build
      run: |
        echo Install dependencies
        npm install
        echo Running build
        npm run build

    - name: Upload to S3
      id: upload
      run: |
        lambdas=`cat lambdas-cd`
        for i in $lambdas; do aws s3 cp build/$i.zip s3://alandev-lambda-functions/deploy/$i/latest.zip; done